spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://dpg-cud874l2ng1s73bea2og-a.oregon-postgres.render.com/airbnb_example
    username: root
    password: 7LYiLvSYziKPMZomVLBMwuogoQidCbpZ
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
server:
  port: ${PORT:10000}
jwt:
  secret: my_super_secret_key_that_is_at_least_32_chars_long
  expiration-ms: 3600000
